const agriData = {
  audio_monitoring: "1737201362376.m4a",
  NBIZ: null,
  enumerator_introduction: {
    enumerator_name: "Sarbagya Shrestha",
    enumerator_id: "Sarbagya Shrestha",
    enumerator_phone: "9823833365",
    building_token_number: "0bywnzaq",
  },
  business_name: "Trilo Krishi Farm",
  b_addr: { ward_no: 2, area_code: "2001", biz_no: 2, locality: "Gyalo Tole" },
  b: {
    op_name: "Trilochan Bhusal",
    opph: "9823833365",
    op_age: 25,
    op_gender: "male",
    op_edu_lvl: "masters_level",
  },
  business_nature: "agriculture_livestock_fish_and_beekeeping_farm",
  business_nature_other: null,
  business_type: null,
  business_type_other: null,
  is_registered: "yes",
  registered_bodies:
    "household_and_microindustries commerce_office ministry_of_health_department ward_office",
  registered_bodies_other: null,
  statutory_status: "individual",
  statutory_status_other: null,
  has_pan: "yes",
  pan_no: 123456789,
  ownership_status: null,
  ownership_status_oth: null,
  hotel: {
    accomodation_type: null,
    room_no: null,
    bed_no: null,
    room_type: null,
    has_hall: null,
    hcpcty: null,
  },
  bag: {
    agri_business: "agriculatural_products",
    bagd: {
      fcrops: "paddy corn wheat millet barley phapar junelo kaguno other",
      fcrop_details_count: "9",
      pulses:
        "pigeon_pea black_gram lentil chickpea soyabean snake_bean bean horse_gram pea other",
      pulse_details_count: "10",
      oseeds: "mustard flax sunflower other",
      oseed_details_count: "4",
      vtables:
        "potato cauliflower cabbage tomato radish carrot turnip capsicum okra brinjal onion string_bean red_kidney_bean pumpkin cucumber bitter_gourd luffa snake_gourd calabash balsam_apple mushroom squice mustard_greens garden_cress spinach colocasia yam other",
      vtable_details_count: "28",
      fruits:
        "mango jackfruit litchi banana lemon orange nibuwa pomelo sweet_orange jyamir sweet_lemon pineapple papaya avocado guava kiwi plum peach pear pomegranate walnut japanese_persimmon hog_plum",
      fruit_details_count: "23",
      spices:
        "coriander garlic turmeric ginger chili_pepper other fenugreek cumin sichuan_pepper black_pepper cinnamomum_tamala",
      spice_details_count: "11",
      ccrops:
        "cotton cardamom tea betel_nut tobacco other sugar_cane coffee rubber jute",
      ccrop_details_count: "10",
      "fcrop_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/fcrop_details",
      fcrop_details: [
        {
          fcrop_ward_no: "2",
          fcrop: "अन्य खद्यान्नबाली",
          fcrop_land: {
            fbigha: 0,
            fkattha: 0,
            fdhur: 0,
            fcrop_area: "0",
            fcnt: null,
          },
          fp: {
            BA01_11: 0,
            BA01_12: 0,
            BA01_13: 0,
            BA01_14: 0,
            fcrop_prod: "0",
          },
          fs: {
            BA01_17: 0,
            BA01_18: 0,
            BA01_19: 0,
            BA01_20: 0,
            fcrop_sales: "0",
          },
          __id: "9f3b302e94449d39c34a36565e472ffae60d596d",
        },
      ],
      "pulse_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/pulse_details",
      pulse_details: [
        {
          pulse_ward_no: "2",
          pulse: "अन्य दालबाली (मस्याङ्, खेसरी,....)",
          pl: {
            pulse_bigha: 0,
            pulse_kattha: 0,
            pulse_dhur: 0,
            pulse_area: "0",
            plnt: null,
          },
          pp: {
            BA02_11: 0,
            BA02_12: 0,
            BA02_13: 0,
            BA02_14: 0,
            pulse_prod: "0",
          },
          ps: {
            BA02_17: 0,
            BA02_18: 0,
            BA02_19: 0,
            BA02_20: 0,
            pulse_sales: "0",
          },
          __id: "23cf1b62f2ae9d400724316c5a2ec0024aa172ef",
        },
      ],
      "oseed_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/oseed_details",
      oseed_details: [
        {
          oseed_ward_no: "2",
          oseed: "अन्य तेलबाली (जैतुन, रायो, ...)",
          osl: {
            os_bigha: 0,
            os_kattha: 0,
            os_dhur: 0,
            oseed_area: "0",
            osnt: null,
          },
          oslp: {
            BA03_10: "1",
            BA03_11: 0,
            BA03_12: 0,
            BA03_13: 0,
            BA03_14: 0,
            oseed_prod: "0",
          },
          osls: {
            BA03_17: 0,
            BA03_18: 0,
            BA03_19: 0,
            BA03_20: 0,
            oseed_sales: "0",
          },
          __id: "d9311af4e37c0e8612791114cc4e51865c1591ef",
        },
      ],
      "vtable_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/vtable_details",
      vtable_details: [
        {
          vtable_ward_no: "2",
          vtable: "आलु",
          vl: {
            vt_bigha: 0,
            vt_kattha: 0,
            vt_dhur: 0,
            vtable_area: "0",
            vtnt: null,
          },
          vp: {
            BA04_10: "1",
            BA04_11: 0,
            BA04_12: 0,
            BA04_13: 0,
            BA04_14: 0,
            vtable_prod: "0",
          },
          vs: {
            BA04_17: 0,
            BA04_18: 0,
            BA04_19: 0,
            BA04_20: 0,
            vtable_sales: "0",
          },
          __id: "f7339496f138a0e66cb4884324ad0288ea98a533",
        },
      ],
      "fruit_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/fruit_details",
      fruit_details: [
        {
          fruit_ward_no: "2",
          fruit: "आँप",
          frl: {
            fruit_bigha: 0,
            fruit_kattha: 0,
            fruit_dhur: 0,
            fruit_area: "0",
            fruit_trees_count: null,
            frnt: null,
          },
          frp: {
            BA05_11: 0,
            BA05_12: 0,
            BA05_13: 0,
            BA05_14: 0,
            fruit_prod: "0",
          },
          frs: {
            BA05_17: 0,
            BA05_18: 0,
            BA05_19: 0,
            BA05_20: 0,
            fruit_sales: "0",
          },
          __id: "6d0292f45c86741165ae8eab5e36b3d50912b777",
        },
      ],
      "spice_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/spice_details",
      spice_details: [
        {
          spice_ward_no: "2",
          spice: "धनिया",
          sl: {
            spice_bigha: 0,
            spice_kattha: 0,
            spice_dhur: 0,
            spice_area: "0",
            spnt: null,
          },
          sp: {
            BA06_11: 0,
            BA06_12: 0,
            BA06_13: 0,
            BA06_14: 0,
            spice_prod: "0",
          },
          ss: {
            BA06_17: 0,
            BA06_18: 0,
            BA06_19: 0,
            BA06_20: 0,
            spice_sales: "0",
          },
          __id: "e9f2cc6804abc821a0b315f4a508eacec02205dc",
        },
      ],
      "ccrop_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/ccrop_details",
      ccrop_details: [
        {
          ccrop_ward_no: "2",
          ccrop: "कपास",
          isBetel: "0",
          cl: {
            betet_trees_count: null,
            cash_bigha: 0,
            cash_kattha: 0,
            cash_dhur: 0,
            ccrop_area: "0",
            ccnt: null,
          },
          cp: {
            BA07_11: 0,
            BA07_12: 0,
            BA07_13: 0,
            BA07_14: 0,
            ccrop_prod: "0",
          },
          cs: {
            BA07_17: 0,
            BA07_18: 0,
            BA07_19: 0,
            BA07_20: 0,
            ccrop_sales: "0",
          },
          __id: "e762fb161cae6947bfbba88b9c27332942d360fb",
        },
      ],
    },
    b_animals: null,
    banimal_details_count: "0",
    b_aprods: null,
    baprod_details_count: "0",
    aquaculture_details: {
      aquaculture_ward_no: null,
      pond_no: null,
      BC01_3: null,
      BC01_5: null,
      BC01_7: null,
      pond_area: null,
      BC01_9: null,
      fish_prod: null,
    },
    apiculture_details: {
      dapi: null,
      apiculture_ward_no: null,
      hive_no: null,
      honey_prod: null,
    },
  },
  investment: 2000000,
  business_location_ownership: "own_house",
  business_location_ownership_oth: null,
  emp: {
    has_partners: "no",
    prt: {
      total_partners: null,
      nepali_male_partners: null,
      nepali_female_partners: null,
      has_foreign_partners: null,
      foreign_male_partners: null,
      foreign_female_partners: null,
      PTOT: null,
      NIF01: null,
    },
    has_involved_family: "no",
    efam: {
      total_involved_family: null,
      male_involved_family: null,
      female_involved_family: null,
      IFTOT: null,
      NIF01: null,
    },
    has_perm_employees: "no",
    etemp: {
      total_perm_employees: null,
      nepali_male_perm_employees: null,
      nepali_female_perm_employees: null,
      has_foreign_perm_employees: null,
      foreign_male_perm_employees: null,
      foreign_female_perm_employees: null,
      frgnpemp: null,
      PERMTOT: null,
      NIF01: null,
    },
    frgnpemp_cnt: null,
    has_temp_employees: "no",
    eperm: {
      total_temp_employees: null,
      nepali_male_temp_employees: null,
      nepali_female_temp_employees: null,
      has_foreign_temp_employees: null,
      foreign_male_temp_employees: null,
      foreign_female_temp_employees: null,
      frgntemp: null,
      TEMPTOT: null,
      NIF01: null,
    },
    frgntemp_cnt: null,
  },
  b_location: {
    type: "Point",
    coordinates: [85.3840339, 27.6895641, 1286.800048828125],
    properties: { accuracy: 20.241 },
  },
  bimg: "1737201343317.jpg",
  bimg_selfie: "1737201359833.jpg",
  meta: {
    instanceID: "uuid:ff7060e4-c0df-4975-bac0-be502a03d753",
    instanceName: "Trilo Krishi Farm Trilochan Bhusal",
  },
  __id: "uuid:ff7060e4-c0df-4975-bac0-be502a03d753",
  __system: {
    submissionDate: "2025-01-18T11:58:09.319Z",
    updatedAt: null,
    submitterId: "32",
    submitterName: "Tester",
    attachmentsPresent: 3,
    attachmentsExpected: 3,
    status: null,
    reviewState: null,
    deviceId: "collect:BgMTfEPWdPuOjfpc",
    edits: 0,
    formVersion: "1",
  },
};
